
ADTankItems = ["Zz'Rot Portal",
               "Banshee's Veil",
               "Dead Man's Plate",
               "Maw of Malmortius",
               "Frozen Mallet",
               "Frozen Heart",
               "Blade of the Ruined King",
               "Locket of the Iron Solari",
               "The Black Cleaver",
               "Ohmwrecker",
               "Randuin's Omen",
               "Titanic Hydra",
               "Righteous Glory",
               "Ruby Sightstone",
               "Trinity Force",
               "Spirit Visage",
               "Sterak's Gage",
               "Sunfire Cape",
               "Thornmail",
               "Warmog's Armor",
               "Wit's End",
               ];
ADTankItemsAmount = ADTankItems.length;


TankItems = ["Zz'Rot Portal",
             "Banshee's Veil",
             "Dead Man's Plate",
             "Zeke's Harbinger",
             "Warmog's Armor",
             "Frozen Heart",
             "Titanic Hydra",
             "Locket of the Iron Solari",
             "Thornmail",
             "Ohmwrecker",
             "Randuin's Omen",
             "Sunfire Cape",
             "Righteous Glory",
             "Ruby Sightstone",
             "Sterak's Gage",
             "Spirit Visage",
             ];
TankItemsAmount = TankItems.length;


APTankItems = ["Rod of Ages",
               "Banshee's Veil",
               "Dead Man's Plate",
               "Abyssal Scepter",
               "Liandry's Torment",
               "Frozen Heart",
               "Iceborn Gauntlet",
               "Locket of the Iron Solari",
               "Zz'Rot Portal",
               "Ohmwrecker",
               "Randuin's Omen",
               "Zeke's Harbinger",
               "Righteous Glory",
               "Ruby Sightstone",
               "Rylai's Crystal Scepter",
               "Spirit Visage",
               "Warmog's Armor",
               "Sunfire Cape",
               "Thornmail",
               ];
APTankItemsAmount = APTankItems.length;


FighterItems = ["Wit's End",
                "Blade of the Ruined King",
                "Frozen Mallet",
                "Guinsoo's Rageblade",
                "Hextech Gunblade",
                "Infinity Edge",
                "Lord Dominik's Regards",
                "Maw of Malmortius",
                "Ravenous Hydra",
                "The Black Cleaver",
                "The Bloodthirster",
                "Guardian Angel",
                "Youmuu's Ghostblade",
                "Phantom Dancer",
                "Trinity Force",
                "Banshee's Veil",
                "Frozen Heart",
                "Randuin's Omen",
                "Spirit Visage",
                "Righteous Glory",
                "Death's Dance",
                "Mercurial Scimitar",
                "Mortal Reminder",
                ];
FighterItemsAmount = FighterItems.length;


ManalessFighterItems = ["Wit's End",
                        "Blade of the Ruined King",
                        "Frozen Mallet",
                        "Guinsoo's Rageblade",
                        "Hextech Gunblade",
                        "Infinity Edge",
                        "Mortal Reminder",
                        "Maw of Malmortius",
                        "Ravenous Hydra",
                        "The Black Cleaver",
                        "The Bloodthirster",
                        "Guardian Angel",
                        "Youmuu's Ghostblade",
                        "Phantom Dancer",
                        "Trinity Force",
                        "Banshee's Veil",
                        "Randuin's Omen",
                        "Spirit Visage",
                        "Death's Dance",
                        "Mercurial Scimitar",
                        "Lord Dominik's Regards",
                        ];
ManalessFighterItemsAmount = ManalessFighter.length;


ADCasterItems = ["Hextech Gunblade",
                 "The Bloodthirster",
                 "The Black Cleaver",
                 "Death's Dance",
                 "Guardian Angel",
                 "Youmuu's Ghostblade",
                 "Trinity Force",
                 "Banshee's Veil",
                 "Muramana",
                 "Essence Reaver",
                 "Maw of Malmortius",
                 "Infinity Edge",
                 "Frozen Heart",
                 "Mercurial Scimitar",
                 "Lord Dominik's Regards",
                 "Mortal Reminder",
                 ];
ADCasterItemsAmount = ADCasterItems.length;

MageItems = ["Abyssal Scepter",
             "Archangel's Staff",
             "Athene's Unholy Grail",
             "Banshee's Veil",
             "Liandry's Torment",
             "Lich Bane",
             "Luden's Echo",
             "Mejai's Soulstealer",
             "Morellonomicon",
             "Nashor's Tooth",
             "Rabadon's Deathcap",
             "Rod of Ages",
             "Rylai's Crystal Scepter",
             "Mikael's Crucible",
             "Void Staff",
             "Will of the Ancients",
             "Zhonya's Hourglass",
             "Guardian Angel",
             "Banner of Command",
             "Ardent Censer",
             ];
MageItemsAmount = MageItems.length;


ManalessMageItems = ["Abyssal Scepter",
                     "Banner of Command",
                     "Guardian Angel",
                     "Banshee's Veil",
                     "Liandry's Torment",
                     "Lich Bane",
                     "Luden's Echo",
                     "Mejai's Soulstealer",
                     "Zhonya's Hourglass",
                     "Nashor's Tooth",
                     "Rabadon's Deathcap",
                     "Will of the Ancients",
                     "Rylai's Crystal Scepter",
                     "Void Staff",
                     ];
ManalessMageItemsAmount = ManalessMageItems.length;


AssassinItems = ["Abyssal Scepter",
                 "Archangel's Staff",
                 "Athene's Unholy Grail",
                 "Banner of Command",
                 "Liandry's Torment",
                 "Lich Bane",
                 "Luden's Echo",
                 "Mejai's Soulstealer",
                 "Morellonomicon",
                 "Nashor's Tooth",
                 "Rabadon's Deathcap",
                 "Rod of Ages",
                 "Rylai's Crystal Scepter",
                 "Zhonya's Hourglass",
                 "Void Staff",
                 "Will of the Ancients",
                 ];
AssassinItemsAmount = AssassinItems.length;


ManalessAssassinItems = ["Abyssal Scepter",
                         "Zhonya's Hourglass",
                         "Will of the Ancients",
                         "Banner of Command",
                         "Liandry's Torment",
                         "Lich Bane",
                         "Luden's Echo",
                         "Mejai's Soulstealer",
                         "Void Staff",
                         "Nashor's Tooth",
                         "Rabadon's Deathcap",
                         "Rylai's Crystal Scepter",
                         ];
ManalessAssassinItemsAmount = ManalessAssassinItems.length;


MarksmanItems = ["Banshee Veil",
                 "Blade of the Ruined King",
                 "Essence Reaver",
                 "Frozen Mallet",
                 "Guardian Angel",
                 "Infinity Edge",
                 "Lord Dominik's Regards",
                 "Manamune",
                 "Mercurial Scimitar",
                 "Phantom Dancer",
                 "Runaan's Hurricane",
                 "Stattikk Shiv",
                 "The Black Cleaver",
                 "The Bloodthirster",
                 "Trinity Force",
                 "Randuin's Omen",
                 "Youmuu's Ghostblade",
                 "Rapid Firecannon",
                 "Mortal Reminder",
                 "Death's Dance",
                 "Guinsoo's Rageblade",
                 ];
MarksmanItemsAmount = MarksmanItems.length;

SupportItems = ["Talisman of Ascension",
                "Frost Queen's Claim",
                "Face of the Mountain",
                "Eye of the Watchers",
                "Eye of the Oasis",
                "Eye of the Equinox",
                ]
SupportItemsAmount = SupportItems.length;

JunglerItems = ["Stalker's Blade - Cinderhulk",
                "Stalker's Blade - Devourer",
                "Stalker's Blade - Runeglaive",
                "Stalker's Blade - Warrior",
                "Skirmisher's Sabre - Cinderhulk",
                "Skirmisher's Sabre - Devourer",
                "Skirmisher's Sabre - Runeglaive",
                "Skirmisher's Sabre - Warrior",
                "Tracker's Knife - Cinderhulk",
                "Tracker's Knife - Devourer",
                "Tracker's Knife - Runeglaive",
                "Tracker's Knife - Warrior",
                ];
JunglerItemsAmount = JunglerItems.length;

Boots = ["Berserker's Greaves - Alacrity",
         "Berserker's Greaves - Captain",
         "Berserker's Greaves - Distortion",
         "Berserker's Greaves - Furor",
         "Berserker's Greaves - Homeguard",
         "Boots of Mobility - Alacrity",
         "Boots of Mobility - Captain",
         "Boots of Mobility - Distortion",
         "Boots of Mobility - Furor",
         "Boots of Mobility - Homeguard",
         "Boots of Swiftness - Alacrity",
         "Boots of Swiftness - Captain",
         "Boots of Swiftness - Distortion",
         "Boots of Swiftness - Furor",
         "Boots of Swiftness - Homeguard",
         "Ionian Boots of Lucidity - Alacrity",
         "Ionian Boots of Lucidity - Captain",
         "Ionian Boots of Lucidity - Distortion",
         "Ionian Boots of Lucidity - Furor",
         "Ionian Boots of Lucidity - Homeguard",
         "Mercury's Treads - Alacrity",
         "Mercury's Treads - Captain",
         "Mercury's Treads - Distortion",
         "Mercury's Treads - Furor",
         "Mercury's Treads - Homeguard",
         "Ninja Tabi - Alacrity",
         "Ninja Tabi - Captain",
         "Ninja Tabi - Distortion",
         "Ninja Tabi - Furor",
         "Ninja Tabi - Homeguard",
         "Sorcerer's Shoes - Alacrity",
         "Sorcerer's Shoes - Captain",
         "Sorcerer's Shoes - Distortion",
         "Sorcerer's Shoes - Furor",
         "Sorcerer's Shoes - Homeguard",
         ];
BootsAmount = Boots.length;