quests = ["You can not recall this game.",
          "You have to destroy the first turret, inhibitor and you have to kill the first dragon and baron.",
          "Your whole team can only buy AD or AP items, decide whitch you choose at the start of the game.",
          "You may not die for the first 20 minutes.",
          "You may not kill for the first 20 minutes.",
          "Make 2 aces before you finish the game.",
          "Immidiately use your ultimate if it is up",
          "One team member can not die this game.",
          "You can only choose champions who have the support tag in there describtion.",
          "Your whole team has to take smite.",
          "You can only purchase trinity forces this game.",
          "Your whole team needs to be full build before you finish the game.",
          "You need to have at least one (core) item before you may hit the outer turrets, at least two (core) items before you can hit the next turret, and so on...",
          "You can only take yordle champions",
          "You can only take animal champions",
          "You can not use smartcast",
          "You can only take champions who have shield abilities. You have to take barrier also.",
          "If you die, you have to go afk for 3 minutes. If another teammate kills someone, you can get back in game.",
          ];
questAmount = quests.length;